##### Application Configuration #####
# For a reference as to what can be specified here, see this:
# https://dropwizard.github.io/dropwizard/manual/configuration.html
#

logging:
  loggers:
    net.spals: ${SAMPLE_DROPWIZARD_WEBAPP_LOGGING_LEVEL:-DEBUG}
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"

server:
  # Use default connector ports
  adminConnectors:
    - type: http
      port: 17071
  applicationConnectors:
    - type: http
      port: 17070
